customhost = "employee.czk0casgmm6r.ap-south-1.rds.amazonaws.com"
customuser = "admindemo"
custompass = "admindemo8530"
customdb = "employee"
custombucket = "addemployeelive"
customregion = "ap-south-1"
